name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - name: Install llvm-10
        run: sudo apt-get install llvm-10 clang-10
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: cargo build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: integritee-node
          path: target/release/integritee-node

  build-skip-ais-check:
    runs-on: ubuntu-18.04
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - name: Install llvm-10
        run: sudo apt-get install llvm-10 clang-10
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: cargo build
        run: cargo build --release --features skip-ias-check

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: integritee-node-skip-ias-check
          path: target/release/integritee-node